version: "3"
networks:
  default:
    external:
      name: netarkivet-net
services:
  wrs:
    build: wrs
    ports:
      - "8883:80"
      - "10443:10443"
    volumes:
      - ./wrs/testdata:/data
      - "bitmag_files:/netarkivet"
      - "fileresolverdb:/db"
  fileresolver:
    build: fileresolver
    ports:
      - "8884:80"
      - "10444:10444"
    volumes:
      - "fileresolverdb:/db"
  fileresolverdb:
    build:
      context: fileresolverdb
      args:
        TESTFILES: "true"
    volumes:
      - "bitmag_files:/netarkivet"
      - "fileresolverdb:/db"
volumes:
  bitmag_files:
  fileresolverdb: